using System.Globalization;
using System.Net;

namespace BruceEDR.Detection;

/// <summary>
/// Everything the heuristics concluded about one DNS name. All ratios are in 0..1 and
/// all values are finite, so the record survives <c>System.Text.Json</c> unchanged.
/// </summary>
public sealed record DomainVerdict
{
    /// <summary>The normalised name that was analysed: trimmed, lower-cased, root dot removed.</summary>
    public string Domain { get; init; } = "";

    /// <summary>0..1 composite DGA likelihood. See <see cref="DomainAnalysis"/> for the weights.</summary>
    public double DgaScore { get; init; }

    /// <summary>True when <see cref="DgaScore"/> clears the threshold on a long enough label.</summary>
    public bool LikelyDga { get; init; }

    /// <summary>The name sits under a known dynamic-DNS or tunnelling provider.</summary>
    public bool IsDynamicDns { get; init; }

    /// <summary>At least one label is IDNA-encoded (<c>xn--</c>), so homograph spoofing is possible.</summary>
    public bool IsPunycode { get; init; }

    /// <summary>Number of dot-separated labels in the whole name.</summary>
    public int LabelCount { get; init; }

    /// <summary>Shannon entropy, in bits per character, of the label that was scored.</summary>
    public double Entropy { get; init; }

    /// <summary>Consonants divided by letters in the scored label. Y counts as a vowel here.</summary>
    public double ConsonantRatio { get; init; }

    /// <summary>Digits divided by total characters in the scored label.</summary>
    public double DigitRatio { get; init; }

    /// <summary>Name plus public suffix, e.g. <c>example.co.uk</c>. Best-effort; see the class remarks.</summary>
    public string RegistrableDomain { get; init; } = "";

    /// <summary>Right-most label. Empty for an empty or non-domain input.</summary>
    public string Tld { get; init; } = "";

    /// <summary>Analyst-facing summary naming the signals that fired, or why none did.</summary>
    public string Explanation { get; init; } = "";

    /// <summary>Shape consistent with data smuggled through DNS labels. Heuristic; see remarks.</summary>
    public bool LooksLikeDnsTunnel { get; init; }
}

/// <summary>
/// Static, offline, allocation-light heuristics over DNS names: domain-generation
/// algorithm (DGA) scoring, dynamic-DNS provider recognition and DNS-tunnelling shape
/// detection. Ships every table inline -- nothing here downloads, resolves or touches
/// the network, so it runs identically on an air-gapped host and in a unit test.
///
/// HONEST ACCURACY STATEMENT. This is a heuristic and it has a real false-positive rate.
/// It has no allow-list of popular domains (shipping one would be a stale, jurisdiction-
/// biased blob), so the following classes of perfectly legitimate name score higher than
/// they should and WILL generate noise if wired straight to a blocking action:
///   * CDN and cloud-generated hostnames. CloudFront distributions (<c>d111111abcdef8</c>),
///     Azure blob and Front Door endpoints, S3 bucket names with build hashes, and
///     Fastly/Akamai edge names are machine-generated by design.
///   * Content-addressed infrastructure: IPFS gateways, container registries and
///     anything that puts a digest in a hostname.
///   * Non-English brands and transliterations. The bigram table is English; a Polish,
///     Turkish or romanised Japanese name looks "unpronounceable" to it and is penalised
///     unfairly. This is a genuine bias, not a rounding error.
///   * Security products themselves. Cloud AV reputation lookups encode file hashes into
///     DNS labels, so an endpoint agent's own traffic is shape-identical to DNS tunnelling.
/// Treat a positive as a lead to enrich, never as a verdict.
///
/// EVASION. A dictionary DGA (concatenating real words, as Suppobox and Matsnu do) scores
/// low here by construction, because its bigram statistics ARE English. Short labels carry
/// too little signal to judge at all and are gated out. None of this looks at registration
/// age, NXDOMAIN rates, or resolved-IP reputation, which is where the strong signal for
/// DGA actually lives.
/// </summary>
public static class DomainAnalysis
{
    /// <summary>Score at or above which <see cref="DomainVerdict.LikelyDga"/> is set.</summary>
    public const double DgaThreshold = 0.60;

    /// <summary>Shortest label that can be called a DGA. Below this the features are noise.</summary>
    public const int MinDgaLabelLength = 8;

    /// <summary>
    /// Shortest label considered when scanning subdomains for the worst offender. Below
    /// this, artefacts like <c>www</c> or <c>api</c> would dominate the maximum for no reason.
    /// </summary>
    private const int MinScannedLabelLength = 7;

    /// <summary>Hard cap on the input length actually analysed, so a hostile 10 MB "name" cannot stall the sensor.</summary>
    private const int MaxAnalysedLength = 1024;

    /// <summary>Weight assigned to a letter pair the bigram table does not contain, per 100,000.</summary>
    private const double MissingBigramWeight = 2.0;

    /// <summary>Mean log10 bigram weight at or above which a label reads as ordinary English.</summary>
    private const double BigramEnglishFloor = 1.95;

    /// <summary>Mean log10 bigram weight at or below which a label reads as random.</summary>
    private const double BigramRandomFloor = 0.85;

    /// <summary>U+FEFF byte-order mark and U+200B zero-width space, stripped during normalisation.</summary>
    private static readonly char[] InvisibleTrimChars = { (char)0xFEFF, (char)0x200B };

    // ------------------------------------------------------------------ tables

    // English letter-bigram frequencies, per 100,000 bigrams, from ordinary running
    // prose. Encoded as one string purely so the table reads as data rather than 250
    // lines of dictionary initialiser. It is deliberately truncated to the head of the
    // distribution: the discriminating power comes from "is this pair common at all",
    // and a long tail of near-zero entries would only blur that.
    private const string BigramTable =
        "th3560 he3070 in2430 er2050 an1990 re1850 on1760 at1490 en1450 nd1350 ti1340 es1340 " +
        "or1280 te1200 of1170 ed1170 is1130 it1120 al1090 ar1070 st1050 to1040 nt1040 ng950 " +
        "se930 ha930 as870 ou870 io830 le830 ve830 co790 me790 de760 hi760 ri730 ro730 ic700 " +
        "ne690 ea690 ra690 ce650 li620 ch600 ll580 be580 ma570 si550 om550 ur540 ca530 el530 " +
        "ta530 la530 ns510 di500 fo500 ho460 pe460 ec460 pr460 no460 ct460 us450 ac450 ot450 " +
        "il440 tr440 ly420 nc420 et410 ut400 ss400 so400 rs400 un400 lo390 wa390 ge380 ie380 " +
        "wh380 ee380 wi370 em370 ad360 ol360 rt360 po350 we350 na350 ul340 ni340 ts340 mo340 " +
        "ow330 pa320 im320 mi300 ai300 sh300 ir290 su290 id290 os290 iv290 ia280 am280 fi280 " +
        "ci280 vi270 pl260 ig260 tu250 ev250 ld250 ry250 mp240 fe240 bl230 ab230 gh220 ty220 " +
        "op220 wo210 sa210 ay210 ex210 ke210 fr210 oo210 av200 ag200 if200 ap200 gr190 od190 " +
        "bo190 sp190 rd190 do190 uc190 bu190 ei180 ov180 by180 rm180 ep180 tt170 oc170 fa170 " +
        "ef170 cu160 rn160 sc160 gi160 da150 yo150 cr150 cl150 du150 ga140 qu140 ue140 ff140 " +
        "ba140 ey140 ls140 va130 um130 pp130 ua130 up130 lu120 go120 ht120 ru120 ug120 ds120 " +
        "lt110 pi110 rc110 rr110 eg110 au110 ck110 ew110 mu110 br110 bi100 pt100 ak100 pu100 " +
        "ui100 rg100 ib100 tl100 ny100 ki100 rk100 ys100 ob100 mm100 fu90 ph90 og90 ms90 ye90 " +
        "ud90 mb80 ip80 ub80 oi80 rl80 gu80 dr80 hr80 cc80 tw70 ft70 wn70 nu70 af70 hu70 nn70 " +
        "eo70 vo70 rv70 nf70 xp70 gn70 sm70 fl70 iz60 ok60 nl60 my60 gl60 aw60 ju60 oa60 eq60 " +
        "sy60 sl60 ps60 jo50 lf50 sk50 yi50 dy50 hy50 ze50 dl50 sw50 bs50 ax40 kn40 ln40 zi40 " +
        "xi40 oe40 ka40 nk40 mn30 xt30 wr30 dg30 ky30 ez30 bt30";

    /// <summary>Indexed by (first - 'a') * 26 + (second - 'a'). Built once, read-only thereafter.</summary>
    private static readonly double[] Bigrams = BuildBigrams();

    /// <summary>
    /// Hand-maintained subset of the Public Suffix List: the two-label suffixes common
    /// enough to matter for registrable-domain extraction. BruceEDR does NOT ship a
    /// full PSL copy, because keeping one current means either a download (forbidden in a
    /// sensor) or a stale blob that quietly rots. The cost is real: exotic suffixes such
    /// as <c>pvt.k12.ma.us</c> or <c>compute.amazonaws.com</c> resolve to a shorter
    /// registrable domain than the PSL would give, which over-groups those names.
    /// </summary>
    private static readonly HashSet<string> MultiPartSuffixes = new(StringComparer.Ordinal)
    {
        "co.uk", "org.uk", "ac.uk", "gov.uk", "net.uk", "me.uk", "sch.uk", "ltd.uk", "plc.uk",
        "com.au", "net.au", "org.au", "edu.au", "gov.au", "asn.au", "id.au",
        "co.nz", "net.nz", "org.nz", "govt.nz", "ac.nz", "school.nz",
        "co.za", "org.za", "net.za", "gov.za", "ac.za", "web.za",
        "co.jp", "ne.jp", "or.jp", "ac.jp", "go.jp", "ad.jp", "lg.jp",
        "co.kr", "or.kr", "ne.kr", "re.kr", "go.kr", "pe.kr",
        "com.br", "net.br", "org.br", "gov.br", "edu.br",
        "com.cn", "net.cn", "org.cn", "gov.cn", "edu.cn", "ac.cn",
        "com.mx", "org.mx", "net.mx", "gob.mx", "edu.mx",
        "com.tr", "net.tr", "org.tr", "gov.tr", "edu.tr",
        "com.sg", "net.sg", "org.sg", "edu.sg", "gov.sg",
        "com.hk", "net.hk", "org.hk", "edu.hk", "gov.hk", "idv.hk",
        "com.tw", "net.tw", "org.tw", "edu.tw", "gov.tw",
        "co.in", "net.in", "org.in", "firm.in", "gen.in", "ind.in", "gov.in", "ac.in", "edu.in",
        "com.ar", "net.ar", "org.ar", "gob.ar", "edu.ar",
        "com.co", "net.co", "org.co",
        "co.il", "org.il", "net.il", "ac.il", "gov.il",
        "com.ua", "net.ua", "org.ua", "gov.ua", "in.ua", "kiev.ua",
        "com.pl", "net.pl", "org.pl", "gov.pl", "edu.pl", "waw.pl",
        "com.ru", "net.ru", "org.ru", "msk.ru", "spb.ru",
        "com.my", "net.my", "org.my", "gov.my", "edu.my",
        "com.ph", "net.ph", "org.ph", "gov.ph",
        "com.vn", "net.vn", "org.vn", "gov.vn", "edu.vn",
        "com.pk", "net.pk", "org.pk", "gov.pk", "edu.pk",
        "com.ng", "net.ng", "org.ng", "gov.ng", "edu.ng",
        "com.eg", "net.eg", "org.eg", "gov.eg", "edu.eg",
        "com.sa", "net.sa", "org.sa", "gov.sa", "edu.sa",
        "co.id", "web.id", "or.id", "ac.id", "go.id", "my.id",
        "co.th", "in.th", "ac.th", "go.th", "or.th",
        "co.ke", "or.ke", "ac.ke", "go.ke",
        "com.pe", "com.ec", "com.uy", "com.ve", "com.do", "com.gt", "com.bo",
        "co.cr", "com.pa", "com.py", "com.ni", "com.sv", "com.hn",
        "gov.us", "k12.us", "state.us",
        "co.at", "or.at", "ac.at", "gv.at",
        "co.hu", "co.ma", "co.no", "co.rs", "co.ug", "co.tz", "co.zw", "co.mz"
    };

    /// <summary>
    /// Dynamic-DNS, free-subdomain and developer-tunnel providers. Malware families reach
    /// for these because a subdomain is free, instant and disposable, and because the
    /// registrable domain belongs to the provider so a takedown is somebody else's problem.
    ///
    /// This is emphatically NOT a badness list. Home labs, self-hosters, IoT cameras and
    /// every developer who has ever demoed a webhook use exactly these services. It is a
    /// context flag that should raise the weight of OTHER signals, nothing more.
    /// </summary>
    private static readonly HashSet<string> DynamicDnsSuffixes = new(StringComparer.Ordinal)
    {
        "duckdns.org", "ddns.net", "hopto.org", "zapto.org", "sytes.net", "myftp.org",
        "myftp.biz", "serveftp.com", "servebeer.com", "servegame.com", "serveminecraft.net",
        "servebbs.com", "servehttp.com", "serveirc.com", "servequake.com", "servepics.com",
        "servemp3.com", "servehalflife.com", "bounceme.net", "redirectme.net", "ddnsking.com",
        "myvnc.com", "onedumb.com", "sellclassics.com", "gotdns.ch", "thruhere.net",
        "webhop.me", "myq-see.com", "3utilities.com", "casacam.net", "dvrdns.org",
        "no-ip.org", "no-ip.biz", "no-ip.info", "no-ip.com", "noip.com",
        "dyndns.org", "dyndns.info", "dyndns-home.com", "homeip.net", "dnsalias.com",
        "afraid.org", "mooo.com", "chickenkiller.com", "crabdance.com", "strangled.net",
        "ignorelist.com", "us.to", "eu.org",
        "dynu.com", "dynu.net", "freeddns.org", "changeip.com", "now-dns.com",
        "cloudns.nz", "cloudns.cc", "cloudns.club", "dnsdynamic.org", "freemyip.com",
        "ngrok.io", "ngrok-free.app", "ngrok.app", "ngrok.dev",
        "trycloudflare.com", "loca.lt", "localtunnel.me", "serveo.net", "pagekite.me",
        "portmap.io", "telebit.io", "tunnelto.dev", "localhost.run", "bore.pub",
        "githubusercontent.com", "pages.dev", "workers.dev", "vercel.app", "netlify.app",
        "onrender.com", "repl.co", "replit.dev", "glitch.me", "herokuapp.com"
    };

    // ------------------------------------------------------------------- public

    /// <summary>
    /// Score one DNS name. Never throws and never returns null for any input, including
    /// null, empty, whitespace, an IP literal, a name with empty labels, or a megabyte of
    /// hostile junk -- a name arriving from a DNS monitor is untrusted data and must not
    /// be able to take down the detection thread.
    /// </summary>
    public static DomainVerdict Analyze(string domain)
    {
        string raw = domain ?? "";
        bool truncated = raw.Length > MaxAnalysedLength;
        if (truncated) raw = raw[..MaxAnalysedLength];

        string norm = NormalizeName(raw);
        if (norm.Length == 0)
        {
            return new DomainVerdict
            {
                Explanation = "empty or unusable name; nothing to analyse."
            };
        }

        // An IP literal is not a domain. Scoring 203.0.113.5 for "pronounceability" would
        // produce a meaningless number that callers would then threshold on.
        if (IPAddress.TryParse(norm, out _))
        {
            return new DomainVerdict
            {
                Domain = norm,
                LabelCount = 0,
                RegistrableDomain = norm,
                Explanation = "literal IP address, not a domain name; DGA and tunnel heuristics do not apply."
            };
        }

        string[] labels = norm.Split('.', StringSplitOptions.RemoveEmptyEntries);
        if (labels.Length == 0)
        {
            return new DomainVerdict
            {
                Domain = norm,
                Explanation = "name contains no usable labels."
            };
        }

        string registrable = Registrable(labels);
        int suffixLabels = Math.Max(0, CountLabels(registrable) - 1);
        int nameIndex = Math.Max(0, labels.Length - suffixLabels - 1);

        // Default subject: the registrable name label, the part the registrant chose.
        string scored = labels[nameIndex];
        double best = ScoreLabel(scored);

        // ... but a family that registers "a1b2c3xyz.duckdns.org" controls only the
        // LEFT-most label; scoring the registrable name would judge the provider's brand
        // and miss the payload entirely. So every operator-chosen label long enough to
        // carry signal is scored and the worst one wins. The cost is more exposure to
        // long machine-generated CDN subdomains, which is the dominant false positive here.
        for (int i = 0; i < nameIndex; i++)
        {
            if (labels[i].Length < MinScannedLabelLength) continue;
            double s = ScoreLabel(labels[i]);
            if (s > best) { best = s; scored = labels[i]; }
        }

        double entropy = Entropy(scored);
        double consonantRatio = ConsonantRatio(scored);
        double digitRatio = DigitRatio(scored);
        bool likelyDga = best >= DgaThreshold && scored.Length >= MinDgaLabelLength;

        bool punycode = false;
        foreach (var l in labels)
            if (l.StartsWith("xn--", StringComparison.Ordinal)) { punycode = true; break; }

        bool dynamicDns = IsDynamicDnsProvider(norm);
        bool tunnel = LooksLikeTunnel(labels, suffixLabels, out string tunnelWhy);

        var why = new List<string>(6);
        if (likelyDga)
            why.Add($"label '{scored}' scores {best.ToString("0.00", CultureInfo.InvariantCulture)} on the DGA heuristic " +
                    $"(entropy {entropy.ToString("0.00", CultureInfo.InvariantCulture)} bits/char, " +
                    $"{(int)Math.Round(consonantRatio * 100)}% consonants, " +
                    $"{(int)Math.Round(digitRatio * 100)}% digits)");
        else
            why.Add($"label '{scored}' scores {best.ToString("0.00", CultureInfo.InvariantCulture)}, below the " +
                    $"{DgaThreshold.ToString("0.00", CultureInfo.InvariantCulture)} DGA threshold");

        if (dynamicDns) why.Add($"registrable domain '{registrable}' is a dynamic-DNS or tunnelling provider (also used legitimately)");
        if (punycode) why.Add("contains an xn-- (IDNA) label, so a homograph of a known brand is possible");
        if (tunnel) why.Add(tunnelWhy);
        if (truncated) why.Add("oversized name was truncated before analysis");

        return new DomainVerdict
        {
            Domain = norm,
            DgaScore = Math.Round(best, 3),
            LikelyDga = likelyDga,
            IsDynamicDns = dynamicDns,
            IsPunycode = punycode,
            LabelCount = labels.Length,
            Entropy = Math.Round(entropy, 3),
            ConsonantRatio = Math.Round(consonantRatio, 3),
            DigitRatio = Math.Round(digitRatio, 3),
            RegistrableDomain = registrable,
            Tld = labels[^1],
            Explanation = string.Join("; ", why) + ".",
            LooksLikeDnsTunnel = tunnel
        };
    }

    /// <summary>
    /// Name plus public suffix (<c>example.co.uk</c>), used to group subdomains that share
    /// an owner. Best effort against the hand-maintained suffix subset described in the
    /// class remarks; returns the input normalised when it has one or two labels.
    /// </summary>
    public static string RegistrableDomain(string domain)
    {
        string norm = NormalizeName(domain ?? "");
        if (norm.Length == 0) return "";
        if (IPAddress.TryParse(norm, out _)) return norm;
        var labels = norm.Split('.', StringSplitOptions.RemoveEmptyEntries);
        return labels.Length == 0 ? "" : Registrable(labels);
    }

    /// <summary>
    /// True when the name is, or sits beneath, a known dynamic-DNS / free-subdomain /
    /// developer-tunnel provider. Matching is on the suffix boundary, so
    /// <c>evilduckdns.org</c> does not match <c>duckdns.org</c>.
    /// </summary>
    public static bool IsDynamicDnsProvider(string domain)
    {
        string norm = NormalizeName(domain ?? "");
        if (norm.Length == 0) return false;

        // Walk the suffixes of the name rather than the provider list, so cost is bounded
        // by label count (at most ~127) instead of by the size of the provider table.
        if (DynamicDnsSuffixes.Contains(norm)) return true;
        int idx = 0;
        while (true)
        {
            int dot = norm.IndexOf('.', idx);
            if (dot < 0 || dot + 1 >= norm.Length) return false;
            if (DynamicDnsSuffixes.Contains(norm[(dot + 1)..])) return true;
            idx = dot + 1;
        }
    }

    // ---------------------------------------------------------------- internals

    /// <summary>
    /// Lower-cases, trims surrounding whitespace and strips the FQDN root dot. A BOM and a
    /// zero-width space are trimmed too, because both are used to smuggle a visually
    /// identical hostname past a naive string comparison; they are written as numeric
    /// escapes so the source stays legible and cannot be mangled by a re-encode.
    /// </summary>
    private static string NormalizeName(string domain)
    {
        string s = domain.Trim().Trim(InvisibleTrimChars);
        // A trailing dot is the DNS root and carries no meaning for these heuristics;
        // leaving it on would silently create an empty final label.
        while (s.Length > 0 && s[^1] == '.') s = s[..^1];
        return s.ToLowerInvariant();
    }

    private static int CountLabels(string s)
    {
        if (s.Length == 0) return 0;
        int n = 1;
        foreach (char c in s) if (c == '.') n++;
        return n;
    }

    private static string Registrable(string[] labels)
    {
        if (labels.Length <= 2) return string.Join('.', labels);
        string lastTwo = labels[^2] + "." + labels[^1];
        return MultiPartSuffixes.Contains(lastTwo)
            ? labels[^3] + "." + lastTwo
            : lastTwo;
    }

    /// <summary>
    /// Composite DGA score for one label, in 0..1.
    ///
    /// EXACT FORMULA:
    ///   bigram    = clamp01((1.95 - meanLog10BigramWeight) / 1.10)
    ///   entropy   = clamp01((H - 3.0) / 1.20)                  H in bits/char
    ///   consonant = clamp01((longestConsonantRun - 3) / 3.0)
    ///   digit     = clamp01((digitRatio - 0.10) / 0.30)
    ///   length    = clamp01((len - 7) / 5.0)
    ///   score     = 0.42*bigram + 0.14*entropy + 0.14*consonant + 0.14*digit + 0.16*length
    ///
    /// WHY BIGRAMS DOMINATE (0.42): at the 8-15 character lengths that matter, Shannon
    /// entropy is nearly useless as a discriminator, because a short label of distinct
    /// characters is at its entropy ceiling whether it spells "microsoft" or "kq3v9zwx".
    /// Pronounceability, measured as bigram plausibility, is the feature that actually
    /// separates them; entropy is kept only as a weak corroborator. The remaining terms
    /// are shape priors: DGA output tends to be longish, consonant-heavy and digit-salted.
    ///
    /// Hyphens and digits terminate consonant runs and are skipped when forming bigram
    /// pairs, so <c>s3-us-west-2</c> is not punished for being unpronounceable.
    /// </summary>
    private static double ScoreLabel(string label)
    {
        if (label.Length == 0) return 0;

        double bigram = Clamp01((BigramEnglishFloor - MeanLogBigram(label)) / (BigramEnglishFloor - BigramRandomFloor));
        double entropy = Clamp01((Entropy(label) - 3.0) / 1.20);
        double consonant = Clamp01((LongestConsonantRun(label) - 3) / 3.0);
        double digit = Clamp01((DigitRatio(label) - 0.10) / 0.30);
        double length = Clamp01((label.Length - 7) / 5.0);

        return Clamp01((0.42 * bigram) + (0.14 * entropy) + (0.14 * consonant) + (0.14 * digit) + (0.16 * length));
    }

    /// <summary>
    /// Mean base-10 log of the per-100,000 frequency of each adjacent letter pair.
    /// Pairs involving a digit or hyphen are skipped entirely. When a label contains no
    /// letter pair at all (<c>1234567</c>) the English floor is returned, i.e. the signal
    /// is withheld rather than guessed -- charging a numeric label for "unpronounceability"
    /// would be scoring the absence of evidence.
    /// </summary>
    private static double MeanLogBigram(string label)
    {
        double sum = 0;
        int pairs = 0;
        for (int i = 0; i + 1 < label.Length; i++)
        {
            char a = label[i], b = label[i + 1];
            if ((a is < 'a' or > 'z') || (b is < 'a' or > 'z')) continue;
            double w = Bigrams[((a - 'a') * 26) + (b - 'a')];
            if (w <= 0) w = MissingBigramWeight;
            sum += Math.Log10(w);
            pairs++;
        }
        return pairs == 0 ? BigramEnglishFloor : sum / pairs;
    }

    /// <summary>
    /// Shannon entropy in bits per character over the label's own symbol distribution.
    /// ASCII is counted in a stack buffer because that is the overwhelmingly common case
    /// on the DNS hot path; non-ASCII (raw UTF-8 in a query name, which does occur) falls
    /// back to a dictionary rather than being dropped, since dropping it would understate
    /// the entropy of exactly the names an attacker would craft.
    /// </summary>
    private static double Entropy(string s)
    {
        if (s.Length == 0) return 0;

        Span<int> ascii = stackalloc int[128];
        Dictionary<char, int>? wide = null;
        foreach (char c in s)
        {
            if (c < 128) { ascii[c]++; continue; }
            wide ??= new Dictionary<char, int>();
            wide.TryGetValue(c, out int seen);
            wide[c] = seen + 1;
        }

        double h = 0, total = s.Length;
        for (int i = 0; i < 128; i++)
        {
            if (ascii[i] == 0) continue;
            double p = ascii[i] / total;
            h -= p * Math.Log2(p);
        }
        if (wide is not null)
        {
            foreach (int n in wide.Values)
            {
                double p = n / total;
                h -= p * Math.Log2(p);
            }
        }
        return h;
    }

    /// <summary>
    /// Consonants over letters. Y is counted as a VOWEL: treating it as a consonant makes
    /// ordinary words such as "rhythm" and "syzygy" register long consonant runs, and the
    /// resulting false positives cost more than the handful of DGA labels that pad with y.
    /// </summary>
    private static double ConsonantRatio(string s)
    {
        int letters = 0, consonants = 0;
        foreach (char c in s)
        {
            if (c is < 'a' or > 'z') continue;
            letters++;
            if (!IsVowel(c)) consonants++;
        }
        return letters == 0 ? 0 : (double)consonants / letters;
    }

    private static double DigitRatio(string s)
    {
        if (s.Length == 0) return 0;
        int digits = 0;
        foreach (char c in s) if (c is >= '0' and <= '9') digits++;
        return (double)digits / s.Length;
    }

    private static int LongestConsonantRun(string s)
    {
        int best = 0, run = 0;
        foreach (char c in s)
        {
            if ((c is >= 'a' and <= 'z') && !IsVowel(c)) { run++; if (run > best) best = run; }
            else run = 0;   // vowels, digits and hyphens all break a run
        }
        return best;
    }

    private static bool IsVowel(char c) => c is 'a' or 'e' or 'i' or 'o' or 'u' or 'y';

    /// <summary>
    /// Shape test for data exfiltrated inside DNS queries (iodine, dnscat2, and the
    /// hand-rolled encoders in commodity loaders). Tunnels must pack payload bytes into
    /// labels, which forces one of: an unusually long left-most label, a base32/hex-looking
    /// left-most label, high entropy in the left-most label, or many long labels.
    ///
    /// This is shape only. It cannot distinguish a tunnel from the several legitimate
    /// systems with the same shape: cloud antivirus reputation lookups (which encode file
    /// hashes), DKIM selectors and key records, ACME dns-01 challenges, DNSBL queries that
    /// embed an address, and NSEC3 hashed names in a signed zone. Expect those in the
    /// results and allow-list them per environment.
    ///
    /// Implemented with linear character scans rather than regular expressions so a hostile
    /// multi-kilobyte label cannot trigger catastrophic backtracking.
    /// </summary>
    private static bool LooksLikeTunnel(string[] labels, int suffixLabels, out string why)
    {
        why = "";
        string left = labels[0];

        if (left.Length >= 40)
        {
            why = $"left-most label is {left.Length} characters, far past what human-chosen names use; consistent with DNS tunnelling";
            return true;
        }

        if (left.Length >= 24 && (IsBase32Like(left) || IsHexLike(left)))
        {
            why = $"left-most label is a {left.Length}-character base32/hex-looking blob; consistent with an encoded DNS tunnel payload";
            return true;
        }

        if (left.Length >= 20)
        {
            double h = Entropy(left);
            if (h >= 3.6)
            {
                why = $"left-most label is {left.Length} characters at {h.ToString("0.00", CultureInfo.InvariantCulture)} bits/char; consistent with encoded data in DNS";
                return true;
            }
        }

        int operatorLabels = Math.Max(0, labels.Length - suffixLabels - 1);
        if (labels.Length >= 7)
        {
            int payload = 0;
            for (int i = 0; i < operatorLabels; i++) payload += labels[i].Length;
            if (payload >= 60)
            {
                why = $"{labels.Length} labels carrying {payload} characters beneath the registrable domain; consistent with chunked DNS tunnelling";
                return true;
            }
        }
        return false;
    }

    /// <summary>RFC 4648 base32 alphabet (lower-cased), optionally padded. Linear scan, no regex.</summary>
    private static bool IsBase32Like(string s)
    {
        int body = s.Length;
        while (body > 0 && s[body - 1] == '=') body--;
        if (body == 0) return false;
        bool sawDigit = false;
        for (int i = 0; i < body; i++)
        {
            char c = s[i];
            if (c is >= 'a' and <= 'z') continue;
            if (c is >= '2' and <= '7') { sawDigit = true; continue; }
            return false;
        }
        // Require at least one 2-7 digit: a pure a-z string is far more likely to be words
        // than base32, and calling every long alphabetic label base32 would be useless.
        return sawDigit;
    }

    private static bool IsHexLike(string s)
    {
        bool sawDigit = false, sawAlpha = false;
        foreach (char c in s)
        {
            if (c is >= '0' and <= '9') { sawDigit = true; continue; }
            if (c is >= 'a' and <= 'f') { sawAlpha = true; continue; }
            return false;
        }
        // Both classes required, for the same reason as base32: "deadbeef" style content
        // needs digits to be hex rather than an English-ish word.
        return sawDigit && sawAlpha;
    }

    private static double Clamp01(double v) => v < 0 ? 0 : v > 1 ? 1 : v;

    private static double[] BuildBigrams()
    {
        var table = new double[26 * 26];
        foreach (var token in BigramTable.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (token.Length < 3) continue;
            char a = token[0], b = token[1];
            if (a is < 'a' or > 'z' || b is < 'a' or > 'z') continue;
            if (!int.TryParse(token.AsSpan(2), NumberStyles.None, CultureInfo.InvariantCulture, out int weight)) continue;
            table[((a - 'a') * 26) + (b - 'a')] = weight;
        }
        return table;
    }
}
